### ISSUE TITLE
Source / Track Arrays

### ISSUE THREAD

**Issue by mediapack-me** [nkoehler/mat-video#3] opened 2018-05-10 10:50 UTC
#### Bug, feature request, or proposal:
Let's call this a feature request. 

#### What is the current behavior?
There do not appear to be properties for source and track.  (Closed captioning, Locale Specific Audio, etc.)

#### What is the expected behavior?
When using an HTML5 video, I expect to be able to add closed captioning (sub titles) in multiple languages.  I expect to be able to expose alternate audio streams to suppor multiple languages.

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>
Examine properties surface in code. 

#### What is the use-case or motivation for changing an existing behavior?
HTML5 video supports **source** and **track**.  It's a must for internationalization.
Closed captions or subtitles are a must for hearing impared.

#### Is there anything else I should know?
These represent "basic" functionality for HTML5. They are not difficult to implement.  Matching the feature set of HTML5, is likely to make your component more attractive to the developers who are working with HTML5 video. (arguably your target audience).

**Comment by nkoehler** [comment] 2018-05-12 20:14
Regarding Sources / Track arrays, that one won't be difficult.  The only issues I'm trying to wrap my head around is:

- Not breaking the existing _src_ attribute.  _mat-video_ is designed to be easy to use as well as functional, so for people just wanting a basic video player, having that attribute is a must.  I was thinking it might be worth creating an _otherSources_ style attribute that takes an array of source tracks.  Likewise, captions could function the same way, by using a _tracks_ style attribute that would take an array of TextTracks.
- Ideally I would like to have a tag within _mat-video_ for source and tracks, just like HTML5 video, but so far I haven't seen anything in angular that can do that cleanly.  The problem is it would be nice to be able to set everything from the template, but this approach needs more thought. I will look and see how _mat-form-field_ does it. ng-content might be the answer...

**Comment by mediapack-me** [comment] 2018-05-12 20:23
They (src and source) are two entirely different things.

So they won't step on each other.

The changes are also non-breaking as you're adding properties.

-- On the last pne... Full Screen Control?

Did you test the case where you are using a router and moving from one route to another?

If you're only testing this on a single route, you're not likely to find the issue.

I described the initial state problem in the comment.

It's important to keep in mind how composing developers will use this.

It's highly unlikely that they're going to just have an app that displays a video on the initial route and does not have any other routes.

**Comment by nkoehler** [comment] 2018-05-13 00:33
This feature will be available this week.

**Comment by nkoehler** [comment] 2018-05-14 23:47
Version 2.2.0 has been released with support for source and track.  Closing this feature request.

**Closed as completed by nkoehler** 2018-05-14 23:47 UTC
Labels: enhancement
